from sqlalchemy.orm import declarative_base

from .domains import (
    Base,
    Role,
    User,
    UserRole,
    StudentProfile,
    Category,
    Task,
    StudentTask,
    Gallery,
    RatingsHistory,
    TaskMedia,
    Achievement,
    UserAchievement,
    Program,
    ProgramBlock,
    ProgramTopic,
    ProgramTask,
    ProgramMaterial,
    Group,
    GroupMember,
    GroupSchedule,
    GroupEnrollment,
    GroupStudentTask,
    GroupRole,
)

__all__ = [
    "Base",
    "Role",
    "User",
    "UserRole",
    "StudentProfile",
    "Category",
    "Task",
    "StudentTask",
    "Gallery",
    "RatingsHistory",
    "TaskMedia",
    "Achievement",
    "UserAchievement",
    "Program",
    "ProgramBlock",
    "ProgramTopic",
    "ProgramTask",
    "ProgramMaterial",
    "Group",
    "GroupMember",
    "GroupSchedule",
    "GroupEnrollment",
    "GroupStudentTask",
    "GroupRole",
]