version: "3.9"

services:

  db:
    image: postgres:15
    container_name: alanko_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alanko
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: alanko_backend
    depends_on:
      - db
      - minio
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      MINIO_INTERNAL_URL: minio:9000
  minio:
    image: minio/minio
    container_name: alanko_minio
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: rGTVTyi3GYs6f667Ng9F25vB5ReB73GQ
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
  postgres_data:
